### ISSUE TITLE
Support translation of "map of Strings"

### ISSUE THREAD

**Issue by emersonsiega** [MohiuddinM/i18n#1]
My app needs to translate a list of strings (a list of countries), and I can't find a way to do that using the yaml file. 

My suggestion is to add this capability to i18n. Just a way to create a setting like:
```
countries: 
   - BR: Brasil
   - SG: Senegal
   - VE: Venezuela
```
so this list can be converted to a Map of Strings. 

This way I can get the correct translation based on the country key
`country['BR']`
