### ISSUE TITLE
messagesMap breaks key-referencing feature

### ISSUE THREAD

**Issue by BjoernPetersen** [MohiuddinM/i18n#17]
As mentioned in #15, the `messagesMap` doesn't handle messages which use other keys, like this example from the README:

```yaml
button:
  save: Save
  load: Load
users:
  welcome(String name): "Hello $name!"
  logout: Logout
```

The reference to $name can't be resolved in the generated messagesMap.

**Comment by BjoernPetersen** [comment]
I'll have to correct myself: the above example is handled correctly, but referencing other keys is not. A rather ham-fisted example:

```yaml
button:
  save: Save
  load: Load
users:
  logout: log out
  logoutPrompt: Are you sure you want to $logout?
```
