### ISSUE TITLE
Can't generate when names include spaces, dashes and underscore

### ISSUE THREAD

**Issue by hugobrancowb** [MohiuddinM/i18n#23]
The yaml example below is being misgenerated due to spaces and dashes; names with undescore even throws during generation (that's why I left it commented). I checked the code and found out how I can help, so you can pin me as responsible for making this improvement if that's the case.

```yaml
kebab-case:
  phrase: "any phrase"

with spaces:
  phrase: "any phrase"

# snake_case:
#   phrase: "any phrase"
```

generated file:
```dart
// ...

class Messages {
	const Messages();
	String get locale => "en";
	String get languageCode => "en";
	Kebab-caseMessages get kebab-case => Kebab-caseMessages(this);
	With spacesMessages get with spaces => With spacesMessages(this);
}

class Kebab-caseMessages {
	final Messages _parent;
	const Kebab-caseMessages(this._parent);
	String get phrase => """any phrase""";
}

class With spacesMessages {
	final Messages _parent;
	const With spacesMessages(this._parent);
	String get phrase => """any phrase""";
}


Map<String, String> get messagesMap => {
	"""kebab-case.phrase""": """any phrase""",
	"""with spaces.phrase""": """any phrase""",
};

```
